source "$PROJECT_DIR/scripts/system_monitoring_functions/cpu_stats.sh"
source "$PROJECT_DIR/scripts/system_monitoring_functions/disk_stats.sh"
source "$PROJECT_DIR/scripts/system_monitoring_functions/process_stats.sh"
source "$PROJECT_DIR/scripts/system_monitoring_functions/system_info.sh"
source "$PROJECT_DIR/scripts/system_monitoring_functions/memory_stats.sh"
source "$PROJECT_DIR/scripts/system_monitoring_functions/logging.sh"