source "$PROJECT_DIR/scripts/ui_scripts/hardware_menu.sh"
source "$PROJECT_DIR/scripts/ui_scripts/ids_menu.sh"
source "$PROJECT_DIR/scripts/ui_scripts/monitor_all.sh"
source "$PROJECT_DIR/scripts/ui_scripts/network_menu.sh"
source "$PROJECT_DIR/scripts/ui_scripts/process_menu.sh"
source "$PROJECT_DIR/scripts/ui_scripts/system_info_menu.sh"
source "$PROJECT_DIR/scripts/ui_scripts/user_menu.sh"
